---
title: "Cleaning the Dataset"
output: html_document
date: "2026-07-24"
---

Function for cleaning the dataset, so that the stata labels don't interfere with the data cleaning process.

```{r}
make_informal_transport <- function(data, columns) {
  
  # Check that all specified columns exist
  missing_columns <- setdiff(
    unname(columns),
    names(data)
  )
  
  if (length(missing_columns) > 0) {
    stop(
      paste(
        "The following columns are missing:",
        paste(missing_columns, collapse = ", ")
      )
    )
  }
  
  
  # Extract and clean required variables
  pas <- clean_code(
    data[[columns[["pas"]]]]
  )
  
  nic <- clean_code(
    data[[columns[["nic"]]]]
  )
  
  enterprise <- clean_code(
    data[[columns[["enterprise"]]]]
  )
  
  enterprise_size <- clean_code(
    data[[columns[["enterprise_size"]]]]
  )
  
  social_security <- clean_code(
    data[[columns[["social_security"]]]]
  )
  
  
  # Convert NIC to five-digit character codes
  nic5 <- ifelse(
    is.na(nic),
    NA_character_,
    sprintf("%05d", nic)
  )
  
  
  # Passenger land transport
  passenger_transport <-
    substr(nic5, 1, 4) %in% c("4921", "4922")
  
  
  # Informal wage/casual employees
  informal_employee <-
    pas %in% c(31, 41, 51) &
    social_security == 8
  
  
  # Informal self-employed workers
  informal_self_employed <-
    pas == 21 |
    (
      pas %in% c(11, 12) &
        enterprise %in% c(1, 2, 3, 4) &
        enterprise_size %in% c(1, 2)
    )
  
  
  # Combine employee and self-employed definitions
  informal_status <-
    informal_employee |
    informal_self_employed
  
  
  # Convert missing logical results to FALSE
  passenger_transport[is.na(passenger_transport)] <- FALSE
  informal_status[is.na(informal_status)] <- FALSE
  
  
  # Add binary variables to the new data frame
  data$transport <- as.integer(
    passenger_transport
  )
  
  data$informal <- as.integer(
    informal_status
  )
  
  
  # Return every observation
  data
}
```

Identifying which columns to clean/look for to identify transport and informal workers.
```{r}
columns17 <- c(
  pas = "b5pt1q3_per_fv",
  nic = "b5pt1q5_per_fv",
  enterprise = "b5pt1q9_per_fv",
  enterprise_size = "b5pt1q10_per_fv",
  social_security = "b5pt1q13_per_fv"
)


columns18_19 <- c(
  pas = "b5pt1q3_per_fv",
  nic = "b5pt1q5_per_fv",
  enterprise = "b5pt1q9_per_fv",
  enterprise_size = "b5pt1q10_per_fv",
  social_security = "b5pt1q13_per_fv"
)


columns19_20 <- c(
  pas = "b5pt1q3_per_fv",
  nic = "b5pt1q5_per_fv",
  enterprise = "b5pt1q9_per_fv",
  enterprise_size = "b5pt1q10_per_fv",
  social_security = "b5pt1q13_per_fv"
)


columns20_21 <- c(
  pas = "b5pt1q3_perv1",
  nic = "b5pt1q5_perv1",
  enterprise = "b5pt1q9_perv1",
  enterprise_size = "b5pt1q10_perv1",
  social_security = "b5pt1q13_perv1"
)


columns22 <- c(
  pas = "b5pt1q3_cperv1",
  nic = "b5pt1q5_cperv1",
  enterprise = "b5pt1q9_cperv1",
  enterprise_size = "b5pt1q10_cperv1",
  social_security = "b5pt1q13_cperv1"
)


columns23 <- c(
  pas = "b5pt1q3_cperv1",
  nic = "b5pt1q5_cperv1",
  enterprise = "b5pt1q9_cperv1",
  enterprise_size = "b5pt1q10_cperv1",
  social_security = "b5pt1q13_cperv1"
)


columns24 <- c(
  pas = "Principal_Status_Code",
  nic = "Principal_Industry_Code",
  enterprise = "Principal_Enterprise_Type",
  enterprise_size = "Principal_Workers_Count",
  social_security = "Principal_Social_Security"
)


columns25 <- c(
  pas = "pas",
  nic = "ind_pas",
  enterprise = "etyp_pas",
  enterprise_size = "wrkr_pas",
  social_security = "ssec_pas"
)

```

Function for adding state identifiers for diff-in-diff
```{r}
add_district_id <- function(data, state_column, district_column) {
  
  # Check that the columns exist
  missing_columns <- setdiff(
    c(state_column, district_column),
    names(data)
  )
  
  if (length(missing_columns) > 0) {
    stop(
      paste(
        "Missing columns:",
        paste(missing_columns, collapse = ", ")
      )
    )
  }
  
  # clean_code() is the function you already defined
  state_code <- clean_code(
    data[[state_column]]
  )
  
  district_code <- clean_code(
    data[[district_column]]
  )
  
  # Standardised character versions
  data$state_code_std <- ifelse(
    is.na(state_code),
    NA_character_,
    sprintf("%02d", state_code)
  )
  
  data$district_code_std <- ifelse(
    is.na(district_code),
    NA_character_,
    sprintf("%03d", district_code)
  )
  
  # Unique identifier: state + district
  data$district_id <- ifelse(
    is.na(state_code) | is.na(district_code),
    NA_character_,
    paste0(
      data$state_code_std,
      "_",
      data$district_code_std
    )
  )
  
  data
}
```

Applying the functions to new data frames for diff-in-diff.
```{r}
#Create data frames for informal transport for each year

informal_transport17_18 <- make_informal_transport(
  data17_18_fv,
  columns17
)

informal_transport18_19 <- make_informal_transport(
  data18_19_fv,
  columns18_19
)

informal_transport19_20 <- make_informal_transport(
  data19_20_fv,
  columns19_20
)

informal_transport20_21 <- make_informal_transport(
  data20_21_fv,
  columns20_21
)

informal_transport22 <- make_informal_transport(
  data22,
  columns22
)

informal_transport23 <- make_informal_transport(
  data23,
  columns23
)

informal_transport24 <- make_informal_transport(
  data24,
  columns24
)

informal_transport25 <- make_informal_transport(
  data25,
  columns25
)


#Adding year variable for time series
informal_transport17_18$year <- 2017
informal_transport18_19$year <- 2018
informal_transport19_20$year <- 2019
informal_transport20_21$year <- 2020
informal_transport22$year <- 2022
informal_transport23$year <- 2023
informal_transport24$year <- 2024
informal_transport25$year <- 2025


#Adding unique district identifiers
informal_transport17_18 <- add_district_id(
  informal_transport17_18,
  state_column = "state_per_fv",
  district_column = "b1q4_per_fv"
)

informal_transport18_19 <- add_district_id(
  informal_transport18_19,
  state_column = "state_per_fv",
  district_column = "b1q4_per_fv"
)

informal_transport19_20 <- add_district_id(
  informal_transport19_20,
  state_column = "state_per_fv",
  district_column = "b1q4_per_fv"
)

informal_transport20_21 <- add_district_id(
  informal_transport20_21,
  state_column = "state_perv1",
  district_column = "distcode_perv1"
)

informal_transport22 <- add_district_id(
  informal_transport22,
  state_column = "state_cperv1",
  district_column = "distcode_cperv1"
)

informal_transport23 <- add_district_id(
  informal_transport23,
  state_column = "state_cperv1",
  district_column = "distcode_cperv1"
)

informal_transport24 <- add_district_id(
  informal_transport24,
  state_column = "State_UT_Code",
  district_column = "District_Code"
)

informal_transport25 <- add_district_id(
  informal_transport25,
  state_column = "st",
  district_column = "dc"
)
```

